# Libs

In [3]:
import pandas as pd
import numpy as np
import json
import os
import datetime as dt
import pickle
from unidecode import unidecode
from sklearn import metrics
from pytimeparse.timeparse import timeparse
import matplotlib.pyplot as plt
import shap
import time
import warnings
from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

warnings.filterwarnings('ignore')

In [4]:
src_path = os.path.abspath(os.getcwd())
root_path = os.path.dirname(src_path)
data_path = os.path.join(root_path, 'dados')
raw_path = os.path.join(data_path, 'raw')
interim_path = os.path.join(data_path, 'interim')
deputados_path = os.path.join(raw_path, 'deputados')
discursos_path = os.path.join(deputados_path, 'discursos')

In [5]:
def flatten_dict(d, parent_key='', sep='_'):
    """
    Flatten a nested dictionary.

    Args:
    - d (dict): The dictionary to flatten.
    - parent_key (str): The base key string.
    - sep (str): The separator between keys.

    Returns:
    - dict: The flattened dictionary.
    """
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

In [6]:
def translate_text(text, max_length=5000):
    text = text.replace('\r', ' ').replace('\n', ' ').replace('\t', ' ').replace('\xa0','')
    if len(text) > max_length:
        translations = []
        for i in range(0, len(text), max_length):
            chunk = text[i:i+max_length]
            translation = translator.translate(chunk, src='pt', dest='en').text
            translations.append(translation)
        return ' '.join(translations)
    else:
        translation_result = translator.translate(text, src='pt', dest='en')
        translated_text = translation_result.text
        if translated_text is None:
            translated_text = ""
        return translated_text

In [7]:
def safe_translate(text, max_retries=3):
    attempt = 0
    while attempt < max_retries:
        try:
            return translate_text(text)
        except Exception as e:
            print(f"Translation error: {e}")
            attempt += 1
            time.sleep(2)  # Wait for 2 seconds before retrying
    return None  # Return None if all attempts fail

In [8]:
def track_progress(future, index):
    if index % 1000 == 0:
        print(f"Completed {index} translations")

In [98]:
def get_sentiment(text, flag):
    if flag == 'blob':
        blob = TextBlob(text)
        return blob.sentiment.polarity, blob.sentiment.subjectivity
    else:        
        sia_score = sia.polarity_scores(text) 
        return sia_score['neg'], sia_score['neu'], sia_score['pos'], sia_score['compound']

# Text Analysis

## Open data

In [9]:
discursos_path

'D:\\Pedro\\Desktop\\Dropbox\\UnB\\Doc\\projects\\api_camara\\dados\\raw\\deputados\\discursos'

In [10]:
# with open(os.path.join(discursos_path,'deputados_discursos_raw_.json'),encoding='ISO-8859-1') as json_file:
#     json_discursos = json.load(json_file)

In [11]:
# len(json_discursos.keys())

In [12]:
# df_list = []
# keys = [x for x in json_discursos.keys()]
# for i, key in enumerate(keys):
#     values_list =  json_discursos[key]
#     if i%100==0:
#         print(f" Appending {key} - ({i}/{len(keys)}) - size {len(values_list)}")
#     for dict_ in values_list:
#         flattened_dict = flatten_dict(dict_)
#         df_ = pd.DataFrame(flattened_dict, index = [key])
#         df_list.append(df_)

In [13]:
# df_speech = pd.concat(df_list)

In [14]:
# df_speech = df_speech.reset_index().rename(columns={'index':'id_deputado'})

In [15]:
# df_speech.to_csv(os.path.join(discursos_path,'deputados_discursos_raw_.json'),index=False)

In [133]:
dict_tematic

{'Agropecuária': ['agropecuária',
  'agronegócio',
  'agrícola',
  'fazenda',
  'plantação',
  'plantações',
  'animais',
  'animal',
  'agrotóxico',
  'pecuária',
  'bovino',
  'suíno',
  'avicultura',
  'piscicultura'],
 'Cidades e Transportes': ['cidades',
  'transportes',
  'trânsito',
  'mobilidade',
  'veículos',
  'urbanismo',
  'predial',
  'metrópole',
  'metropolitano',
  'território',
  'cargas',
  'acessibilidade',
  'passageiros',
  'motorizado',
  'terminais',
  'metroviário',
  'metrô',
  'ferroviário',
  'ferrovia',
  'hidroviário',
  'hidrovia',
  'ciclovias',
  'aeroportos'],
 'Ciência, Tecnologia e comunicações': ['ciência',
  'tecnologia',
  'televisão',
  'inovação',
  'rádio',
  'cnpq',
  'capes'],
 'Economia & Consumidor': ['economia',
  'econômic',
  'indústria',
  'capital',
  'juros',
  'finança',
  'consumidor',
  'dívida',
  'comércio',
  'imposto',
  'empresário',
  'investidor',
  'macroeconomi',
  'câmbio',
  'empresa',
  'inflação'],
 'Direitos Humanos': ['direitos humanos', 'LGBT', 'minorias'],
 'Educação, cultura e esportes': ['educação',
  'cultura',
  'esporte',
  'MEC',
  'aluno',
  'estudante',
  'universidade',
  'escola',
  'professor',
  'campus',
  'docente',
  'pedagogia',
  'creche',
  'ensino',
  'FUNDEB',
  'primeira infância',
  'PROUNI',
  'institutos federais',
  'mensalidade',
  'charter'],
 'Meio ambiente e energia': ['meio ambiente',
  'energia',
  'eólica',
  'elétrica',
  'PETROBRAS',
  'ELETROBRAS',
  'combustíveis fósseis',
  'hidroelétrica',
  'termoelétrica',
  'gás',
  'renovável',
  'renováveis',
  'fotovoltaica',
  'poluição',
  'biomassa',
  'etanol',
  'biocombustível',
  'estufa',
  'metano',
  'particulados',
  'biodiesel'],
 'Política e administração pública': ['política',
  'administração pública',
  'estado',
  'município'],
 'Relações exteriores': ['relações exteriores',
  'diplomacia',
  'itamaraty',
  'embaixador',
  'política externa',
  'política comercial',
  'comércio internacional',
  'ernesto araújo',
  'mercosul',
  'trump',
  'ex-tarifário',
  'exporta',
  'barreira tarifária',
  'importação',
  'importações',
  'união européia',
  'venezuela',
  'alfândega',
  'OCDE',
  'conteúdo local',
  'imigração',
  'conselho de segurança',
  'fronteira',
  'oriente médio',
  'china',
  'consul'],
 'Saúde': ['saúde',
  'SUS',
  'médicos',
  'médico',
  'médica',
  'vacinação',
  'remédio',
  'remédios'],
 'Segurança': ['segurança',
  'violência',
  'maioridade penal',
  'presídio',
  'presídios',
  'assassinatos',
  'estupro',
  'maria da penha',
  'feminicídio'],
 'Trabalho, previdência e assistência': ['trabalho',
  'previdência',
  'assistência social']}

In [16]:
dict_tematic = {
    'Agropecuária': [
        'agro',
        'agrícola',
        'fazenda',
        'plantação',
        'plantações',
        'animais',
        'animal',
        'agrotóxico',
        'pecuária',
        'bovino',
        'suíno',
        'avicultura',
        'piscicultura'
                ],
    'Cidades e Transportes':[
        'cidades',
        'transportes',
        'trânsito',
        'mobilidade',
        'veículos',
        'urbanismo',
        'predial',
        'metrópole',
        'metropolitano',
        'território',
        'cargas',
        'acessibilidade',
        'passageiros',
        'motorizado',
        'terminais',
        'metroviário',
        'metrô',
        'ferroviário',
        'ferrovia',
        'hidroviário',
        'hidrovia',
        'ciclovias',
        'aeroportos'
        ],
    'Ciência, Tecnologia e comunicações':[
        'ciência',
        'tecnologia',
        'televisão',
        'inovação',
        'rádio',
        'cnpq',
        'capes',
        ],
    'Economia & Consumidor':[
        'economia',
        'econômic',
        'indústria',
        'capital',
        'juros',
        'finança',
        'consumidor',
        'dívida',
        'comércio',
        'imposto',
        'empresário',
        'empresa',
        'investidor',
        'macroeconomi',
        'câmbio',
        'empresa',
        'inflação',
        ],
    'Direitos Humanos':[
        'direitos humanos',
        'LGBT',
        'minorias',
        'gay',
        'lésbic'
    ],
    'Educação, cultura e esportes':[
        'educação',
        'cultura',
        'esporte',
        'MEC',
        'aluno',
        'estudante',
        'universi',
        'escola',
        'professor',
        'campus',
        'docente',
        'pedagogia',
        'creche',
        'ensino',
        'FUNDEB',
        'infância',
        'PROUNI',
        # 'institutos federais',
        'mensalidade',
        'charter',
        ],
    'Meio ambiente e energia':[
        'meio ambiente',
        'energia',
        'eólica',
        'elétrica',
        'PETROBRAS',
        'ELETROBRAS',
        'combustíveis fósseis',
        'hidroelétrica',
        'termoelétrica',
        'gás',
        'renovável',
        'renováveis',
        'fotovoltaica',
        'poluição',
        'biomassa',
        'etanol',
        'biocombustível',
        'estufa',
        'metano',
        'particulados',
        'biodiesel',
        ],
    'Política e administração pública':[
        'política',
        'administração pública',
        'estado',
        'município',
        ],
    'Relações exteriores':[
        'relações exteriores',
        'diplomacia',
        'itamaraty',
        'embaixador',
        'política externa',
        'política comercial',
        'comércio internacional',
        # 'ernesto araújo',
        'mercosul',
        'trump',
        'ex-tarifário',
        'exporta',
        'barreira tarifária',
        'importação',
        'importações',
        'união européia',
        'venezuela',
        'alfândega',
        'OCDE',
        'conteúdo local',
        'imigração',
        'conselho de segurança',
        'fronteira',
        'oriente médio',
        'china',
        'consul'
        ],
    'Saúde' :[
        'saúde',
        'SUS',
        'médicos',
        'médico',
        'médica',
        'vacinação',
        'remédio',
        'remédios'
        ],
    'Segurança': [
        'segurança',
        'violência',
        'maioridade penal',
        'presídio',
        'presídios',
        'assassinatos',
        'estupro',
        'maria da penha',
        'feminicídio' 
        ],
    'Trabalho, previdência e assistência':[
        'trabalho',
        'previdência',
        'assistência social',
        ]
}

In [17]:
# with open(os.path.join(interim_path,'tematics-words.json'), 'w') as f:
#     json.dump(dict_tematic, f, ensure_ascii=False, indent=4)

In [18]:
with open(os.path.join(interim_path,'tematics-words.json')) as f:
    dict_tematic = json.load(f)

In [19]:
df_speech = pd.read_csv(os.path.join(discursos_path,'deputados_discursos_raw_.json'))
df_speech = df_speech.dropna(subset = ['transcricao'])
df_speech.dataHoraInicio = pd.to_datetime(df_speech.dataHoraInicio)

In [20]:
df_dep_info = pd.read_csv(os.path.join(interim_path,'dep_info.csv'), sep = ';')

In [21]:
list_of_lists = df_dep_info.nome.str.split(' ').to_list()
stop_words1 = [item.upper() for sublist in list_of_lists for item in sublist]

In [22]:
stop_words2 = ['GILDENEMYR', 'OTACI',
              "Acre","AC","Alagoas","AL","Amapá","AP","Amazonas","AM","Bahia","BA","Ceará","CE","Distrito","DF","Espírito","Santo","ES","Goiás","GO","Maranhão","MA",
              "Mato","Grosso","MT","sul","MS","Minas","Gerais","MG","Pará","PA","Paraíba","PB","paraná","PR","Pernambuco","PE","Piauí","PI","Rio","Janeiro","RJ","Norte","RN",
              "RS","Rondônia","RO","Roraima","RR","Santa","Catarina","SC","São","Paulo","SP","Sergipe","SE","Tocantins","TO",
              "DEM","PP","PDT","PODE","PSB","PT","PRB","CIDADANIA","PSOL","MDB","PCdoB","PSD","PL","PTB","PROS","PSDB","PSC","PSL","SOLIDARIEDADE","NOVO","AVANTE","PATRIOTA","PV","S.PART.","REDE","PMN","PHS",
              'líder','deputada','sem','bloco','deputado','dr','-',".",",","...","(",")",'sra','','sras','srs','sr.','sr','sra.','sem','sra','presidente','deputados','deputadas','pela',
              'ordem','revisão','orador','discurso','de','a','o','que','e','do','da','em','um','para','e','com','uma','os','no','se','na','por','as','dos','como','foi','ao','ele','das','tem', 
              'a','seu','sua','ou','ser','quando','há','é','nós','nos','ja','esta','eu','tambem','so','pelo','pela','ate','isso','ela','entre','era','depois','aos','ter','seus',
              'quem','nas','me','esse','eles','estao','voce','essa','num','suas','meu','as','minha','tem','numa','pelos','elas','havia',
              'seja','qual','sera','nos','tenho','lhe','deles','essas','esses','pelas','este','fosse','dele','tu','te','voces','vos','lhes','meus','minhas','teu','tua','teus'
              ]

In [23]:
stop_words = stop_words1 + stop_words2
stop_words = list(set(stop_words))
stop_words = [x.lower() for x in stop_words]

In [24]:
len(stop_words)

4439

In [25]:
regex = r"(?u)\b[^\W\d]{3,}\b"

In [26]:
df_speech = df_speech.merge(df_dep_info[['id', 'nome', 'nomeCivil']].rename(columns = {"id":"id_deputado"}), how='left', on = "id_deputado")

In [128]:
df_speech

,id_deputado,dataHoraInicio,dataHoraFim,uriEvento,faseEvento_titulo,faseEvento_dataHoraInicio,faseEvento_dataHoraFim,tipoDiscurso,urlTexto,urlAudio,urlVideo,keywords,sumario,transcricao,nome,nomeCivil
0,1595,1900-01-01 15:20:00,NaN,NaN,Ordem do Dia,NaN,NaN,DISCUSSÃO,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"TRÂNSITO, MULTA DE TRÂNSITO, RADAR ELETRÔNICO,...",Congratulações à Presidência pela condução dos...,O SR. MILTON VIEIRA (PRB - SP. Para discutir.)...,MILTON,Aristides Augusto Milton
1,1872,1900-01-01 11:01:00,NaN,NaN,Ordem do Dia,NaN,NaN,ORIENTAÇÃO DE BANCADA,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"ORIENTAÇÃO DE BANCADA, VETO 38/2017, VETO TOTA...",NaN,O SR. PEDRO CUNHA LIMA (PSDB - PB. Para encami...,CUNHA LIMA,Antonio José Maria da Cunha Lima
2,1872,1900-01-01 15:30:00,NaN,NaN,Breves Comunicações,NaN,NaN,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"RÔMULO GOUVEIA, DEPUTADO FEDERAL, FALECIMENTO,...",NaN,O SR. PEDRO CUNHA LIMA (PSDB - PB. Para uma br...,CUNHA LIMA,Antonio José Maria da Cunha Lima
3,4440,1900-01-01 11:00:00,NaN,NaN,Ordem do Dia,NaN,NaN,ENCAMINHAMENTO DE VOTAÇÃO,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"PROJETO DE LEI, CRÉDITO ESPECIAL, ALOCAÇÃO, AP...",Encaminhamento da votação do Projeto de Lei 4...,O SR. JOSÉ CARLOS ALELUIA (Bloco/PFL – BA. Par...,JOSÉ CARLOS,José Carlos de Carvalho
4,4440,1900-01-01 11:00:00,NaN,NaN,Ordem do Dia,NaN,NaN,DISCUSSÃO,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"PROJETO DE LEI, CRÉDITO ESPECIAL, ENCARGOS FIN...","Discussão do Projeto de Lei 28, de 2001-CN (Ab...",O SR. JOSÉ CARLOS ALELUIA (Bloco/PFL – BA. Par...,JOSÉ CARLOS,José Carlos de Carvalho
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454857,220558,2023-03-23 10:40:00,NaN,NaN,Breves Comunicações,NaN,NaN,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"Ensino médio,reforma\r\nLinguagem inclusiva de...",Contrariedade à implantação de linguagem neutr...,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Zé Trovão,MARCOS ANTONIO PEREIRA GOMES
454858,220558,2023-03-23 11:12:00,NaN,NaN,Breves Comunicações,NaN,NaN,PELA ORDEM,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"Trabalho por aplicativo,Regulamentação profiss...","Contrariedade à pretendida regulamentação, pel...",O SR. ZÉ TROVÃO (PL - SC. Pela ordem. Sem revi...,Zé Trovão,MARCOS ANTONIO PEREIRA GOMES
454859,220558,2023-03-27 18:36:00,NaN,NaN,Breves Comunicações,NaN,NaN,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"Governo federal,Economia,Joinville (SC),Recurs...",Gestão desastrosa do Governo Luiz Inácio Lula ...,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Zé Trovão,MARCOS ANTONIO PEREIRA GOMES
454860,220558,2023-03-28 14:12:00,NaN,NaN,Breves Comunicações,NaN,NaN,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,"Agronegócio,Fundação Instituto de Pesquisa Eco...",NaN,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Zé Trovão,MARCOS ANTONIO PEREIRA GOMES
454861,220558,2023-03-29 14:40:00,NaN,NaN,Breves Comunicações,NaN,NaN,BREVES COMUNICAÇÕES,https://imagem.camara.gov.br/dc_20b.asp?largur...,NaN,NaN,NaN,NaN,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Zé Trovão,MARCOS ANTONIO PEREIRA GOMES

In [27]:
# a = df_speech.merge(df_dep_info[['id', 'nome', 'nomeCivil']].rename(columns = {"id":"id_deputado"}), how='left', on = "id_deputado")
# a = a[a.dataHoraInicio.duplicated(keep=False)][['dataHoraInicio', 'id_deputado', 'nome', 'nomeCivil', 'transcricao']]
# a['name_aux'] = a['transcricao'].str.split(' - ').str[0]
# a['name_aux'] = a['name_aux'].str.split(' \(').str[0].replace('O SR. ','', regex=True).replace('O SRA. ','', regex=True)
# a[['id_deputado', 'nome', 'nomeCivil','name_aux']].drop_duplicates().to_excel(os.path.join(interim_path, 'speech_aux.xlsx'), index=False)

In [28]:
# a[a.dataHoraInicio>'1901-01-01'].sort_values('dataHoraInicio')
# [['id_deputado', 'nome', 'nomeCivil', 'transcricao']].drop_duplicates()

## TF-IDF

**TF-IDF - Term Frequency-Inverse Document Frequency.**:
 - It is a statistical measure used to evaluate the importance of a word in a document relative to a collection of documents (corpus). The TF-IDF value increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus, which helps to adjust for the fact that some words appear more frequently in general.
    
**Components:**

- **Term Frequency (TF):** Measures how frequently a term occurs in a document. The more a term appears in a document, the higher its TF score.

   - $\text{TF}(t) = \frac{\text{Number of times term } t \text{ appears in a document}}{\text{Total number of terms in the document}}$
  
- **Inverse Document Frequency (IDF):** Measures how important a term is. While computing TF, all terms are considered equally important. However, some terms like "is", "of", and "that" may appear a lot but have little importance. Thus, we need to weigh down the frequent terms while scaling up the rare ones.

   - $\text{IDF}(t) = \log\left(\frac{\text{Total number of documents}}{\text{Number of documents with term } t \text{ in it}}\right)$

- **TF-IDF:** The TF-IDF score for a term is the product of its TF and IDF scores.

   - $\text{TF-IDF}(t) = \text{TF}(t) \times \text{IDF}(t)$

**How `TfidfVectorizer` Works:**

1. **Tokenization:** Splits the text into words (tokens).
2. **Building the Vocabulary:** Creates a dictionary of all unique words across the corpus.
3. **Calculating TF-IDF Scores:** Computes the TF-IDF score for each word in each document.

**Parameters Used in Your Code:**

- `min_df=10`: Ignore terms that appear in fewer than 10 documents.
- `max_df=0.95`: Ignore terms that appear in more than 95% of the documents.
- `stop_words=stop_words`: A list of words to ignore (commonly used words that are not informative).
- `token_pattern=regex`: A regex pattern to tokenize the text.

**Application to Deputies' Speeches:**

By applying `TfidfVectorizer` to deputies' speeches, you are converting their speeches into numerical features that can be used for various machine learning tasks, such as:

- **Text Classification:** Classify speeches by topics, sentiments, or authors.
- **Clustering:** Group similar speeches together.
- **Information Retrieval:** Find speeches similar to a query speech.
- **Feature Extraction:** Extract meaningful features for further analysis.

In [37]:
id_cols = ['id_deputado', 'nome', 'dataHoraInicio', 'nomeCivil']
year_list = df_speech.dataHoraInicio.dt.year.unique()

In [38]:
dict_tfidf = {x:{'words':[],'data':[]} for x in dict_tematic}

In [39]:
df_final = pd.DataFrame()
for year in sorted(year_list[1:]):
    print(year)
    df_speech_f = df_speech[df_speech.dataHoraInicio.dt.year == year]
    # df_speech_f = df_speech_f.merge(df_dep_info[['id', 'nome', 'nomeCivil']].rename(columns = {"id":"id_deputado"}), how='left', on = "id_deputado")
    df_speech_f = df_speech_f.set_index(['id_deputado', 'nome', 'dataHoraInicio'])
    
    vectorizer = TfidfVectorizer(min_df= 10,  max_df = 0.95, stop_words = stop_words, token_pattern = regex)
    
    X = vectorizer.fit_transform(df_speech_f['transcricao'])
    y = df_speech_f['nomeCivil']
    
    features = vectorizer.get_feature_names_out()
    
    tfidf_dense = X.todense()
    tfidf_df = pd.DataFrame(tfidf_dense, columns=features)
    tfidf_df = pd.concat([y.reset_index(), tfidf_df],axis=1)
    
    df_id = tfidf_df[id_cols]    
    for k,v in dict_tematic.items():
        filtered_list = []

        values = [word for phrase in v for word in phrase.split()]

        for phrase in values:
            words = phrase.split()
            if len(phrase) > 1:
                if all(word in features for word in words):
                    filtered_list.extend(words)
            else:
                filtered_list.extend([item for item in features if words[0] in item and item not in filtered_list])

        filtered_list = list(dict.fromkeys(filtered_list))

        df_id = pd.concat([df_id,tfidf_df[filtered_list].mean(axis=1)],axis=1).rename(columns = {0:k})
        # print('theme:',k)
        # print(' - words related:',v)
        # print(' - words in the speech:',filtered_list) 
    
    df_id['year'] = year
    df_final = pd.concat([df_final, df_id])

2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023

In [130]:
tfidf_df.head()

,id_deputado,nome,dataHoraInicio,nomeCivil,abaixo,abandonadas,abandonados,abandono,abastecimento,abc,...,órfãos,órgão,órgãos,ônibus,ônus,última,últimas,últimos,única,único
0,73701,Benedita da Silva,2023-02-08 13:56:00,BENEDITA SOUZA DA SILVA SAMPAIO,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07454
1,73701,Benedita da Silva,2023-02-09 09:24:00,BENEDITA SOUZA DA SILVA SAMPAIO,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
2,73701,Benedita da Silva,2023-02-28 14:08:00,BENEDITA SOUZA DA SILVA SAMPAIO,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
3,73701,Benedita da Silva,2023-03-01 14:52:00,BENEDITA SOUZA DA SILVA SAMPAIO,0.0,0.0,0.076904,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000
4,73701,Benedita da Silva,2023-03-02 10:12:00,BENEDITA SOUZA DA SILVA SAMPAIO,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000

In [106]:
df_final

,id_deputado,nome,nome,dataHoraInicio,nomeCivil,Agropecuária,Cidades e Transportes,"Ciência, Tecnologia e comunicações",Economia & Consumidor,Direitos Humanos,"Educação, cultura e esportes",Meio ambiente e energia,Política e administração pública,Relações exteriores,Saúde,Segurança,"Trabalho, previdência e assistência",year
0,73468,ANTÔNIO CARLOS KONDER REIS,0.000000,2000-10-05 14:02:00,ANTÔNIO CARLOS KONDER REIS,0.000000,0.000000,0.000000,0.002691,0.0,0.002244,0.000000,0.015380,0.004310,0.000000,0.000000,0.006255,2000
1,73468,ANTÔNIO CARLOS KONDER REIS,0.040821,2000-10-05 16:18:00,ANTÔNIO CARLOS KONDER REIS,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.016305,2000
2,73468,ANTÔNIO CARLOS KONDER REIS,0.000000,2000-10-17 14:58:00,ANTÔNIO CARLOS KONDER REIS,0.000000,0.000000,0.012182,0.000000,0.0,0.000000,0.000000,0.026715,0.004572,0.000000,0.000000,0.000000,2000
3,73468,ANTÔNIO CARLOS KONDER REIS,0.015619,2000-11-06 17:26:00,ANTÔNIO CARLOS KONDER REIS,0.000000,0.004488,0.004725,0.006387,0.0,0.001107,0.002338,0.013279,0.007233,0.003765,0.000000,0.000000,2000
4,73468,ANTÔNIO CARLOS KONDER REIS,0.071640,2000-11-08 10:16:00,ANTÔNIO CARLOS KONDER REIS,0.002898,0.012431,0.000000,0.005517,0.0,0.003426,0.000000,0.042059,0.009778,0.000000,0.032162,0.008554,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2571,220558,Zé Trovão,0.000000,2023-03-23 10:40:00,MARCOS ANTONIO PEREIRA GOMES,0.014285,0.000000,0.000000,0.000000,0.0,0.013927,0.000000,0.000000,0.000000,0.007414,0.000000,0.000000,2023
2572,220558,Zé Trovão,0.000000,2023-03-23 11:12:00,MARCOS ANTONIO PEREIRA GOMES,0.000000,0.000000,0.000000,0.037172,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023
2573,220558,Zé Trovão,0.000000,2023-03-27 18:36:00,MARCOS ANTONIO PEREIRA GOMES,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.007862,0.051926,0.004399,0.007166,0.000000,0.000000,2023
2574,220558,Zé Trovão,0.000000,2023-03-28 14:12:00,MARCOS ANTONIO PEREIRA GOMES,0.047561,0.000000,0.000000,0.004565,0.0,0.013172,0.000000,0.000000,0.011479,0.000000,0.014910,0.000000,2023
2575,220558,Zé Trovão,0.000000,2023-03-29 14:40:00,MARCOS ANTONIO PEREIRA GOMES,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.016573,0.006610,0.000000,0.000000,0.000000,2023

## Translate speechs

In [ ]:
translator = Translator()

In [ ]:
i=0
translation_list = []
speechs = df_speech['transcricao'].to_list()

In [155]:
for txt in speechs:    
    
    if i%5000 == 0:
        print(i,len(txt))
    try:
        translation = translate_text(txt)        
    except:
        time.sleep(1)
        try:
            translation = translate_text(txt)
        except:
            time.sleep(5)
            try:
                translation = translate_text(txt)
            except:
                translation = np.nan
                time.sleep(5)
                
    df_tmp = pd.DataFrame({'transcricao':txt,'traducao':translation},index=[i])        
    translation_list.append(df_tmp)
     
    if i%50000 == 0:        
        df_speechs_aux = pd.concat(translation_list)
        df_speechs_aux.to_csv(os.path.join(interim_path, 'translation_speechs_.csv'),index=False)   
    
    i += 1

405000 522
406000 205
407000 3054
408000 1416
409000 471
410000 17915
411000 379
412000 2902
413000 863
414000 3175
415000 1391
416000 1870
417000 3899
418000 785
419000 4372
420000 5031
421000 2997
422000 731
423000 2814
424000 221
425000 2534
426000 916
427000 3439
428000 3540
429000 1333
430000 1206
431000 3204
432000 1206
433000 2018
434000 566
435000 1766
436000 2774
437000 2261
438000 4943
439000 3161
440000 290
441000 7025
442000 2709
443000 1151
444000 4811
445000 8983
446000 1306
447000 598
448000 5063
449000 1546
450000 402
451000 255
452000 2032
453000 1658
454000 905
455000 3999
456000 3328
457000 2382
458000 1201
459000 1055
460000 2600
461000 577
462000 1924
463000 1410
464000 1481
465000 2037
466000 2484
467000 5733
468000 5785
469000 4749
470000 472
471000 745
472000 274
473000 3144
474000 3984
475000 1899
476000 839
477000 2705
478000 577
479000 5604
480000 780
481000 2468
482000 990
483000 5371
484000 596
485000 2670
486000 583
487000 5160
488000 1388
489000 1824
490000 3756
491000 1063
492000 19684
493000 791
494000 1700
495000 3615
496000 4592
497000 1425
498000 4181
499000 4512
500000 4130
501000 1341
502000 3028
503000 3181
504000 722
505000 6636
506000 2086
507000 2053
508000 770
509000 4587
510000 2351
511000 1142
512000 4176
513000 3777
514000 2664
515000 1147
516000 512
517000 2437
518000 4629
519000 689
520000 1930
521000 4367
522000 5750
523000 417
524000 888
525000 1125
526000 3073
527000 1944
528000 771
529000 3400
530000 445
531000 4285
532000 5047
533000 3229
534000 2623
535000 2176
536000 6138
537000 2032
538000 7586
539000 1026
540000 4186
541000 468
542000 3336
543000 3414
544000 2230
545000 4263
546000 17478
547000 3684
548000 1375
549000 755
550000 5918
551000 4796
552000 2937
553000 1435
554000 1265
555000 3653
556000 3350
557000 5248
558000 7474
559000 500
560000 626
561000 1082
562000 3040
563000 986
564000 475
565000 2793
566000 1892
567000 1316
568000 4267
569000 3230
570000 687
571000 338
572000 1742
573000 3146
574000 355
575000 14407
576000 4407
577000 3333
578000 2813
579000 6045
580000 2665
581000 2217
582000 2458
583000 2479
584000 6202
585000 2257
586000 1211
587000 1446
588000 3641
589000 840
590000 1038
591000 742
592000 909
593000 596
594000 3271
595000 2103
596000 15302
597000 3311
598000 3419
599000 987
600000 1527
601000 972
602000 858
603000 2202
604000 1944
605000 2525
606000 12248
607000 3062
608000 264
609000 14454
610000 814
611000 1730
612000 1381
613000 1262
614000 499
615000 911
616000 2852
617000 1432
618000 2735
619000 6671
620000 250
621000 1055
622000 2579
623000 4546
624000 4260
625000 2884
626000 1089
627000 6507
628000 9884
629000 1451
630000 1513
631000 31894
632000 2259
633000 2515
634000 741
635000 1747
636000 708
637000 3951
638000 5456
639000 1229
640000 355
641000 3099
642000 1458
643000 1879
644000 840
645000 4946
646000 1936
647000 828
648000 548
649000 2561
650000 760
651000 3350
652000 731
653000 3975
654000 1999
655000 476
656000 761
657000 2482
658000 2300
659000 1420
660000 2368
661000 1854
662000 2374
663000 2591
664000 4058
665000 4811
666000 3520
667000 3994
668000 2661
669000 4542
670000 3900
671000 2249
672000 2176
673000 3673
674000 15676
675000 2219
676000 4638
677000 1355
678000 5184
679000 957
680000 1344
681000 1121
682000 355
683000 3861
684000 686
685000 1120
686000 3799
687000 16383
688000 2496
689000 1671
690000 5091
691000 3409
692000 443
693000 6181
694000 1094
695000 2005
696000 598
697000 343
698000 2873
699000 821
700000 956
701000 1116
702000 3399
703000 997
704000 112
705000 3647
706000 2034
707000 8025
708000 876
709000 1429
710000 7305
711000 1647
712000 1019
713000 1731
714000 3242
715000 977
716000 1012
717000 333
718000 2375
719000 2753
720000 981
721000 1694
722000 3244
723000 2633
724000 2040
725000 901
726000 831
727000 411
728000 1112
729000 1964
730000 8434
731000 1006
732000 851
733000 522
734000 983
735000 3103
736000 785
737000 790
738000 4233
739000 663
740000 7716
741000 823
742000 2748
743000 666
744000 5351
745000 7197
746000 2349
747000 1010
748000 523
749000 2456
750000 1201
751000 2733
752000 5065
753000 4304
754000 2860
755000 1226
756000 871
757000 1685
758000 2002
759000 2983
760000 755
761000 1524
762000 2239
763000 4178
764000 4517
765000 1942
766000 790
767000 2453
768000 2413
769000 3928
770000 642
771000 1061
772000 2091
773000 2585
774000 2456
775000 967
776000 1669
777000 853
778000 3121
779000 981
780000 2138
781000 980
782000 3818
783000 590
784000 400
785000 5171
786000 1473
787000 4269
788000 982
789000 748
790000 9987
791000 3930
792000 410
793000 2439
794000 3156
795000 1070
796000 5821
797000 992
798000 739
799000 283
800000 2032
801000 497
802000 7254
803000 805
804000 1104
805000 2013
806000 7686
807000 3623
808000 2293
809000 961
810000 1148
811000 757
812000 992
813000 955
814000 1171
815000 302
816000 743
817000 717
818000 941
819000 1013
820000 1549
821000 3119
822000 2915
823000 472
824000 2477
825000 838
826000 1879
827000 2941
828000 404
829000 4516
830000 1259
831000 11455
832000 902
833000 309
834000 6046
835000 3819
836000 815
837000 482
838000 2778
839000 718
840000 1071
841000 303
842000 1123
843000 658
844000 1034
845000 1730
846000 926
847000 1004
848000 3945
849000 732
850000 741
851000 1251
852000 2372
853000 2673
854000 1026
855000 455
856000 911
857000 971
858000 756
859000 2078

In [196]:
len(translation_list)

454862

In [259]:
df_translation = pd.concat(translation_list)
df_translation.to_csv(os.path.join(interim_path, 'translation_speechs_raw.csv'),index=False, sep = ';')

In [200]:
df_speech_ = df_speech[['id_deputado', 'dataHoraInicio', 'faseEvento_titulo','tipoDiscurso', 'keywords', 'sumario', 'transcricao']]
df_speech_ =  df_speech_.merge(df_translation.reset_index(drop = True).drop('transcricao',axis=1), left_index=True, right_index=True)

In [ ]:
speechs_missing = df_speech_[df_speech_.traducao.isna()].transcricao.to_list()

In [233]:
translation_list2 = []
for i,txt in enumerate(speechs_missing):
    print(i)
    translation = translate_text(txt)        
    df_tmp = pd.DataFrame({'transcricao':txt,'traducao':translation},index=[i])        
    translation_list2.append(df_tmp)

In [257]:
df_translation2 = pd.concat(translation_list2)

In [255]:
df_speech_ = df_speech_.merge(df_translation2.rename(columns = {'traducao':'traducao_aux'}),how='left', on=['transcricao'])
df_speech_.loc[df_speech_['traducao'].isna(), 'traducao'] = df_speech_['traducao_aux']
df_speech_ = df_speech_.drop('traducao_aux',axis=1)

In [260]:
df_speech_.to_csv(os.path.join(interim_path, 'translation_speechs.csv'),index=False, sep = ';')

## Sentiment Analyzer

1. **VADER (Valence Aware Dictionary and sEntiment Reasoner) nuanced analysis**:
    - The SentimentIntensityAnalyzer is designed to capture subtle variations in sentiment, which is why it provides separate scores for negative, neutral, and positive sentiments. The compound score gives an overall sentiment assessment. In this case, it recognized both positive and neutral aspects of the sentence but determined the overall sentiment as positive.
       - **neg**: Proportion of the text that is negative (0.0 means no negativity detected).
       - **neu**: Proportion of the text that is neutral (0.651 means the majority of the text is neutral).
       - **pos**: Proportion of the text that is positive (0.349 means a significant portion is positive).
       - **compound**: An aggregated score that summarizes the overall sentiment. It ranges from -1 (most negative) to +1 (most positive). A score of 0.6468 indicates a positive sentiment.

2. **TextBlob Results:**:
   - TextBlob simplifies the sentiment into two scores: polarity and subjectivity. For your text, TextBlob interpreted the sentiment as maximally positive (polarity=1.0) and highly subjective (subjectivity=1.0). TextBlob doesn’t break down sentiment into components like VADER does but gives a straightforward positive or negative assessment.
        - **polarity**: This score ranges from -1 (very negative) to +1 (very positive). A polarity of 1.0 indicates the text is extremely positive.
        - **subjectivity**: This score ranges from 0 (very objective) to 1 (very subjective). A subjectivity of 1.0 indicates that the text is entirely based on personal opinions or feelings.

In [72]:
sia = SentimentIntensityAnalyzer()

In [71]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Pichau\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [82]:
df_speech_transl = pd.read_csv(os.path.join(interim_path, 'translation_speechs.csv'), sep = ';')

In [100]:
df_speech_transl['neg'], df_speech_transl['neu'], df_speech_transl['pos'], df_speech_transl['compound'] = zip(*df_speech_transl['traducao'].apply(lambda x: get_sentiment(x, 'sia')))

In [102]:
df_speech_transl['polarity'], df_speech_transl['subjectivity'] = zip(*df_speech_transl['traducao'].apply(lambda x: get_sentiment(x, 'blob')))

In [103]:
df_speech_transl

,id_deputado,dataHoraInicio,faseEvento_titulo,tipoDiscurso,keywords,sumario,transcricao,traducao,neg,neu,pos,compound,polarity,subjectivity
0,1595,1900-01-01 15:20:00,Ordem do Dia,DISCUSSÃO,"TRÂNSITO, MULTA DE TRÂNSITO, RADAR ELETRÔNICO,...",Congratulações à Presidência pela condução dos...,O SR. MILTON VIEIRA (PRB - SP. Para discutir.)...,Mr.Milton Vieira (PRB - SP. To discuss.) - Mr....,0.059,0.825,0.116,0.7728,0.185833,0.580833
1,1872,1900-01-01 11:01:00,Ordem do Dia,ORIENTAÇÃO DE BANCADA,"ORIENTAÇÃO DE BANCADA, VETO 38/2017, VETO TOTA...",NaN,O SR. PEDRO CUNHA LIMA (PSDB - PB. Para encami...,Mr.Pedro Cunha Lima (PSDB - PB. To forward. Wi...,0.021,0.941,0.038,0.0953,-0.001364,0.361667
2,1872,1900-01-01 15:30:00,Breves Comunicações,BREVES COMUNICAÇÕES,"RÔMULO GOUVEIA, DEPUTADO FEDERAL, FALECIMENTO,...",NaN,O SR. PEDRO CUNHA LIMA (PSDB - PB. Para uma br...,Mr.Pedro Cunha Lima (PSDB - PB. For a brief co...,0.057,0.679,0.265,0.9989,0.370000,0.521772
3,4440,1900-01-01 11:00:00,Ordem do Dia,ENCAMINHAMENTO DE VOTAÇÃO,"PROJETO DE LEI, CRÉDITO ESPECIAL, ALOCAÇÃO, AP...",Encaminhamento da votação do Projeto de Lei 4...,O SR. JOSÉ CARLOS ALELUIA (Bloco/PFL – BA. Par...,Mr.José Carlos Aleluia (Bloco/PFL - BA. To for...,0.039,0.868,0.093,0.8841,0.234935,0.541688
4,4440,1900-01-01 11:00:00,Ordem do Dia,DISCUSSÃO,"PROJETO DE LEI, CRÉDITO ESPECIAL, ENCARGOS FIN...","Discussão do Projeto de Lei 28, de 2001-CN (Ab...",O SR. JOSÉ CARLOS ALELUIA (Bloco/PFL – BA. Par...,Mr.José Carlos Aleluia (Block/PFL - BA. To dis...,0.018,0.910,0.072,0.8126,0.071429,0.659524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454857,220558,2023-03-23 10:40:00,Breves Comunicações,BREVES COMUNICAÇÕES,"Ensino médio,reforma\r\nLinguagem inclusiva de...",Contrariedade à implantação de linguagem neutr...,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Mr.Zé Trovão (PL - SC. Without speaker review....,0.105,0.809,0.087,-0.7434,0.037290,0.586468
454858,220558,2023-03-23 11:12:00,Breves Comunicações,PELA ORDEM,"Trabalho por aplicativo,Regulamentação profiss...","Contrariedade à pretendida regulamentação, pel...",O SR. ZÉ TROVÃO (PL - SC. Pela ordem. Sem revi...,Mr.Zé Trovão (PL - SC. By order. Without revie...,0.073,0.812,0.116,0.6291,0.037778,0.552778
454859,220558,2023-03-27 18:36:00,Breves Comunicações,BREVES COMUNICAÇÕES,"Governo federal,Economia,Joinville (SC),Recurs...",Gestão desastrosa do Governo Luiz Inácio Lula ...,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Mr.Zé Trovão (PL - SC. Without review of the s...,0.078,0.805,0.117,0.9578,0.218933,0.574113
454860,220558,2023-03-28 14:12:00,Breves Comunicações,BREVES COMUNICAÇÕES,"Agronegócio,Fundação Instituto de Pesquisa Eco...",NaN,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Mr.Zé Trovão (PL - SC. Without speaker review....,0.113,0.782,0.104,-0.7324,-0.034947,0.562264
454861,220558,2023-03-29 14:40:00,Breves Comunicações,BREVES COMUNICAÇÕES,NaN,NaN,O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...,Mr.Zé Trovão (PL - SC. No speaker review.) - P...,0.171,0.770,0.060,-0.9952,-0.169180,0.534091

In [112]:
df_speech_transl[-3:-2].transcricao.item()

'O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orador.) - Sr. Presidente, quero inicialmente saudá-lo e dizer que é sempre uma honra ver a sessão ser presidida por V.Exa., um homem que tem responsabilidade, que tem bom ânimo e que conduz os trabalhos sempre com muita grandeza. Agradeço aos nobres pares da Direita ou da conhecida pela Esquerda como extrema-direita. Na verdade, nós não estamos na extrema-direita, nós somos a extrema necessidade para um país que corre grandes riscos na mão do tal "bandidim de nove dedos" \x97 é assim que eu vou chamá-lo; vou usar até um pronome meio neutro, para depois não ser processado \x97, que só faz o Brasil andar para trás. Noventa e oito mil: este é o número dos pontos, é a nossa pontuação que caiu na Bolsa de Valores. Isso reflete os 20% que o Brasil está regredindo todos os dias. Mas alguém vai à outra tribuna encher a boca para dizer que o descondenado, mais conhecido como "bandido", está fazendo política séria. Nunca vi este desgoverno fazer política séria. Este desgoverno não tem vergonha na cara nem ao menos responsabilidade com os mais pobres. Eu digo isso embasado na informação de que muitos empregos estão sendo perdidos todos os dias no Brasil por irresponsabilidade. Fico mais atônito ainda porque já faz 86 dias que ele assumiu, e a picanha não apareceu ainda nesses 86 dias. Cadê a picanha? A abóbora já apareceu, Deputado. Ele agora quer enfiar abóbora nas famílias, porque a abóbora é grande e sustenta uma família. "Mas você prometeu picanha e agora quer dar abóbora?" Ele não tem vergonha na cara, junto com todos os seus Ministros, a exemplo do Flávio Dino, que circula pela Favela da Maré, que não tem coragem de determinar uma intervenção no Rio Grande do Norte, para salvar as vidas que estão sendo perdidas por causa do crime organizado. O pior de tudo aconteceu com Joinville, em Santa Catarina, o nosso Estado. Setenta e seis por cento dos catarinenses são "bolsonaristas". No nosso Município, simplesmente cortaram 40% do orçamento da nossa saúde pública. Sr. Presidente, quero que V.Exa. ouça este dado, que é muito importante para o Brasil: Joinville é a cidade do Brasil que mais investe no SUS, que tem responsabilidade com os seus conterrâneos. Agora tiraram do orçamento dela simplesmente 40%. Nós já estávamos recebendo valores que não nos atendiam 100%, e agora piorou a nossa situação. Neste desgoverno, nós vamos receber 10 milhões por mês. Isso não é suficiente para a folha de pagamento do SUS, isso não ajuda o nosso Município, que tem quase 800 mil pessoas. Fica aqui registrado o meu repúdio. Nós vamos para cima deste desgoverno, deste cidadão que não tem responsabilidade! Que Deus abençoe a nossa Nação. Muito obrigado.'

In [113]:
df_speech_transl[-3:-2].traducao.item()

'Mr.Zé Trovão (PL - SC. Without review of the speaker.) - Mr. President, I want initially healthy and say that it is always an honor to see the session to be presided by you., A man who has responsibility, who has goodCEO and that always conducts work with great greatness.I thank the noble pairs of the right or the known to the left as far right.In fact, we are not in the far right, we are the extreme need for a country that runs great risks in the hand of such "nine-fingers" that\'s how I will call it;I will even use a kind of neutral pronoun, so that it is not processed, which only makes Brazil walk backwards.Ninety -eight thousand: This is the number of points, it is our score that fell on the stock exchange.This reflects the 20% that Brazil is regressing every day.But someone goes to the other tribune to fill his mouth to say that the discount, better known as "bandit", is doing serious politics.I have never seen this mischief do serious politics.This mischief is not ashamed in the face or even responsibility to the poorest.I say this based on the information that many jobs are being lost every day in Brazil for irresponsibility.I am even more astonished because it has been 86 days since he took over, and the picanha has not appeared in these 86 days.Where\'s the picanha?The pumpkin has already appeared, deputy.He now wants to stick pumpkin in families, because the pumpkin is large and supports a family."But did you promise picanha and now want to give pumpkin?"He is not ashamed in the face, along with all his ministers, such as Flávio Dino, who circulates through the Favela da Maré, who does not have the courage to determine an intervention in Rio Grande do Norte, to save the lives that are being lost bycause of organized crime.Worst of all happened to Joinville, in Santa Catarina, our state.Seventy -six percent of Santa Catarina are "pockets".In our municipality, they simply cut 40% of the budget of our public health.Mr. President, I want you.Listen to this data, which is very important for Brazil: Joinville is the city of Brazil that invests most in SUS, which has responsibility with its countrymen.Now they have taken from her budget simply 40%.We were already receiving values \u200b\u200bthat did not meet us 100%, and now has worsened our situation.In this misleading, we will receive 10 million a month.This is not enough for SUS payroll, it doesn\'t help our municipality, which has almost 800,000 people.Here is my repudiation.We go up this mischief, this citizen who has no responsibility!May God bless our nation.Thank you very much.'

In [114]:
txt = df_speech_transl[-3:-2].traducao.item()
len(txt)

2572

In [117]:
sia.polarity_scores(txt)

{'neg': 0.078, 'neu': 0.805, 'pos': 0.117, 'compound': 0.9578}

In [119]:
TextBlob(txt).sentiment

Sentiment(polarity=0.21893267651888343, subjectivity=0.5741133004926108)

In [132]:
df_speech_transl.iloc[-3]

id_deputado                                                     220558
dataHoraInicio                                     2023-03-27 18:36:00
faseEvento_titulo                                  Breves Comunicações
tipoDiscurso                                       BREVES COMUNICAÇÕES
keywords             Governo federal,Economia,Joinville (SC),Recurs...
sumario              Gestão desastrosa do Governo Luiz Inácio Lula ...
transcricao          O SR. ZÉ TROVÃO (PL - SC. Sem revisão do orado...
traducao             Mr.Zé Trovão (PL - SC. Without review of the s...
neg                                                              0.078
neu                                                              0.805
pos                                                              0.117
compound                                                        0.9578
polarity                                                      0.218933
subjectivity                                                  0.574113
Name: 454859, dtype: object

In [131]:
df_final.iloc[-3]

id_deputado                                                  220558
nome                                                      Zé Trovão
nome                                                            0.0
dataHoraInicio                                  2023-03-27 18:36:00
nomeCivil                              MARCOS ANTONIO PEREIRA GOMES
Agropecuária                                                    0.0
Cidades e Transportes                                           0.0
Ciência, Tecnologia e comunicações                              0.0
Economia & Consumidor                                           0.0
Direitos Humanos                                                0.0
Educação, cultura e esportes                                    0.0
Meio ambiente e energia                                    0.007862
Política e administração pública                           0.051926
Relações exteriores                                        0.004399
Saúde                                                      0.007166
Segurança                                                       0.0
Trabalho, previdência e assistência                             0.0
year                                                           2023
Name: 2573, dtype: object